#!/usr/bin/python

# i3 config generator/switcher
# by Oliver Kraitschy
# http://okraits.de okraits@arcor.de

from os import path, getenv, listdir, system
from sys import argv
import argparse
from subprocess import Popen, PIPE

## Not needed until --init works.
# from shutil import copyfile

class j4Config():
    """ Used to organize all of the configuration files. """
    def __init__(self, theme_name=None, tolerant=False, verbose=False, quiet=False, *config_paths):

        self.raw_configs = {}
        self.configs = {}
        if theme_name is not None:
            try:
                self.readConfig(themes_list[theme_name], name="theme")
            except KeyError:
                prefix = "Warning: " if tolerant else "Error: "
                print(prefix + "theme %s does not exist." % theme_name)
                print_info(usage=False)
                if not tolerant:
                    exit(1)
        for config_path in config_paths:
            # Gets all config blocks.
            self.readThemefile(config_path)
        # Combines config blocks.
        self.consolidateConfigs()

    def readConfig(self, file_path, name=None):
        """ Takes a file and extracts all of the blocks from it. """
        if name is None:
            name = file_path.split(os.sep)[-1]
        with open(file_path, 'r') as file:
            self.raw_configs[name] = {}
            for line in file:
                status = None
                if "$i3-" in line:
                    status = line.strip()
                    if status not in self.raw_configs[name]:
                        self.raw_configs[name][status] = ''
                elif status is not None:
                    self.raw_configs[name][status] += line
        except IOError:
            print("Error: could not open %s" % file_path)
        
        # try to open i3 base config file
        try:
            basefile = open(i3_BASECONFIG_PATH, "r")
        except IOError:
            print("Error: i3 base config file could not be opened.")
            exit(1)
        # read all lines of base config into list
        baselines_list.extend(basefile.readlines())
        basefile.close()
        
        # append all additional configuration files
        for appendFilename in args.append:
            try:
                appendFile = open(i3_PATH + "/" + appendFilename, "r")
            except IOError:
                print("Error: file %s could not be opened." % appendFilename)
                exit(1)
            # read all lines of appendFile into list
            baselines_list.extend(appendFile.readlines())
            appendFile.close()
        
        # try to open i3 config file
        try:
            configfile = open(i3_CONFIG_PATH, "w")
        except IOError:
            print("Error: i3 config file could not be created.")
            exit(1)
        
        # iterate over base config lines, write all to config file
        # and insert theme config at the right place
        for line in baselines_list:
            if line.lstrip().startswith("# $i3-theme-window"):
                if args.theme is not None:
                    configfile.write(windowText)
            elif line.lstrip().startswith("# $i3-theme-bar"):
                if args.theme is not None:
                    configfile.write(barText)
            else:
                configfile.write(line)
        configfile.flush()
        configfile.close()

# paths
SYSTEM_THEME_PATH = "/usr/share/j4-make-config-git/themes"
THEME_PATH = ""
i3_PATH = ""
i3_BASECONFIG_PATH = ""
i3_CONFIG_PATH = ""
# variables for config processing
themes_list = {}
baselines_list = []
windowActive = False
barActive = False
windowText = ""
barText = ""
commandString = ""

def detectConfigDir():
    i3_PATH = None
    if path.exists(getenv("HOME") + "/.i3/config.base"):
        i3_PATH = getenv("HOME") + "/.i3"
    elif path.exists(getenv("HOME") + "/.config/i3/config.base"):
        i3_PATH = getenv("HOME") + "/.config/i3"
    elif getenv("XDG_CONFIG_HOME") is not None:
        if path.exists(getenv("XDG_CONFIG_HOME") + "/i3/config.base"):
            i3_PATH = getenv("XDG_CONFIG_HOME") + "/i3"
    return i3_PATH

usage_info = """i3 config generator/switcher\n
Usage examples:
===============
Create config file and include a specific theme:
\tj4-make-config <theme-name>
Create config file without including a theme:
\tj4-make-config none
Include a specific/no theme and reload i3 after creating the config file:
\tj4-make-config -r <theme-name>|none
Append additional configuration from files in the i3 config directory:
\tj4-make-config -a <file-name> -a <another-file-name> <theme-name>|none
Append additional configuration and reload i3 after creating the config file:
\tj4-make-config -r -a <file-name> <theme-name>|none
Run j4-make-config with the most recently used arguments:
\tj4-make-config"""

theme_info = ("\nAvailable themes:\n"
        "=================\n"
        "\n".join(sorted(themes_list.keys())))

def print_info(usage=True, themes=True):
    if usage:
        print(usage_info)
    if themes:
        print(theme_info)

""" Instead of executing, I just do a split and load the values into the argparser. """
def get_j4_cache():
    if path.exists(getenv("HOME") + "/.j4-make-config.rc"):
        try:
            rcfile = open(getenv("HOME") + "/.j4-make-config.rc", "r")
        except IOError:
            print("Error: file %s could not be opened." % (getenv("HOME") + "/.j4-make-config.rc"))
            exit(1)
        commandString = rcfile.read()
        rcfile.close()
        print("Executing: " + commandString)
        return commandString.split()[1:]
    else:
        print("Error: file %s does not exist yet." % (getenv("HOME") + "/.j4-make-config.rc"))
        exit(1)

def set_j4_cache(theme_name, interactive=False):
    if interactive:
        commandString = argv[0] + ' -r ' + theme_name
    else:
        commandString = ' '.join(argv)
    try:
        rcfile = open(getenv("HOME") + "/.j4-make-config.rc", "w")
    except IOError:
        print("Error: file %s could not be opened." % (getenv("HOME") + "/.j4-make-config.rc"))
        exit(1)
    rcfile.write(commandString)
    rcfile.flush()
    rcfile.close()

if __name__ == "__main__":
    ## Configuring the work environment.
    # detect i3 configuration directory
    if not detectConfigDir():
        print("Error: i3 base config file could not be found.")
        exit(1)
    else:
        # set paths
        THEME_PATH = i3_PATH + "/themes"
        i3_BASECONFIG_PATH = i3_PATH + "/config.base"
        i3_CONFIG_PATH = i3_PATH + "/config"
        # fill themes dictionary with names and paths
        try:
            if path.exists(SYSTEM_THEME_PATH):
                for theme in listdir(SYSTEM_THEME_PATH):
                    themes_list[theme] = SYSTEM_THEME_PATH + "/" + theme
            if path.exists(THEME_PATH):
                for theme in listdir(THEME_PATH):
                    themes_list[theme] = THEME_PATH + "/" + theme
        except (IOError, OSError):
            print("Error: No themes found.")
            exit(1)

    # TODO: Figure out how to get -h to work even if the config base doesn't exist yet.
    parser = argparse.ArgumentParser(description='i3 config generator/switcher',
            usage=usage_info+"\n"+theme_info)
    parser.add_argument(
            '-i', '--interactive', action='store_true',
            help="Uses rofi to select a theme.")
    parser.add_argument('-r', '--refresh', action='store_true',
            help='Reload i3 after creating the config file.')
    parser.add_argument('-a', '--append', action='append',
            metavar='<file-name>', default=list(),
            help="Append additional configuration files located "
                 "in the i3 config directory.")
    parser.add_argument('theme', action='store', nargs='?',
            metavar='<theme-name>', default=None,
            help="Create a config file using a specific theme.")
    """
    # This doesn't work just yet.
    parser.add_argument('--init', action='store_true',
            help="Automatically create `config.base`.")
    """

    ## Parsing the arguments.
    if len(argv)==1:
        args = parser.parse_args(get_j4_cache())
    else:
        args = parser.parse_args() 

    """
    if args.init:
        copyfile(i3_CONFIG_PATH, i3_BASECONFIG_PATH)
        print("Created config.base in %s." % i3_PATH)
        exit(0)
    """

    if args.interactive:
        ps = Popen("echo '%s' | rofi -width 30 -dmenu -p 'Set i3 theme:'" % \
                ("\n".join(sorted(themes_list.keys()))),
                stdout=PIPE, stderr=PIPE, shell=True, universal_newlines=True)
        for line in ps.stdout:
            args.theme = line[:-1]
            args.refresh = True
            set_j4_cache(args.theme, interactive=True)
        if args.theme is None:
            exit(0)

    if args.theme is not None:
        # try to open given filename
        try:
            themefile = open(themes_list[args.theme], "r")
        except (KeyError, IOError):
            print("Error: theme %s does not exist." % args.theme)
            print_info(usage=False)
            exit(1)
        
        # read themefile, create section strings
        for line in themefile:
            if "$i3-theme-window" in line:
                windowActive = True
                barActive = False
            elif "$i3-theme-bar" in line:
                windowActive = False
                barActive = True
            else:
                if windowActive and not barActive:
                    windowText += line
                elif not windowActive and barActive:
                    barText += line
        themefile.close()
    
    # try to open i3 base config file
    try:
        basefile = open(i3_BASECONFIG_PATH, "r")
    except IOError:
        print("Error: i3 base config file could not be opened.")
        exit(1)
    # read all lines of base config into list
    baselines_list.extend(basefile.readlines())
    basefile.close()
    
    # append all additional configuration files
    for appendFilename in args.append:
        try:
            appendFile = open(i3_PATH + "/" + appendFilename, "r")
        except IOError:
            print("Error: file %s could not be opened." % appendFilename)
            exit(1)
        # read all lines of appendFile into list
        baselines_list.extend(appendFile.readlines())
        appendFile.close()
    
    # try to open i3 config file
    try:
        configfile = open(i3_CONFIG_PATH, "w")
    except IOError:
        print("Error: i3 config file could not be created.")
        exit(1)
    
    # iterate over base config lines, write all to config file
    # and insert theme config at the right place
    for line in baselines_list:
        if line.lstrip().startswith("# $i3-theme-window"):
            if args.theme is not None:
                configfile.write(windowText)
        elif line.lstrip().startswith("# $i3-theme-bar"):
            if args.theme is not None:
                configfile.write(barText)
        else:
            configfile.write(line)
    configfile.flush()
    configfile.close()

    if args.refresh:
        system("i3-msg reload")
    
    # store commandstring in rc file
    set_j4_cache(args.theme, interactive=False)
    exit(0)
